#!/bin/bash
# install_git-filters

BASEDIR="$( cd "$( dirname "$0" 2>/dev/null)" && pwd 2>/dev/null)"

if ! sudo grep -q "^export PATH=\$PATH:$BASEDIR/filters$" /etc/profile > /dev/null 2>&1; then
	sudo sh -c "echo \"export PATH=\\\$PATH:$BASEDIR/filters\" >> /etc/profile"
fi

/usr/bin/git config --global filter.mwb.clean mwb-clean
/usr/bin/git config --global filter.mwb.smudge mwb-smudge

export PATH=$PATH:$BASEDIR/filters
