#!/bin/bash
# mwb-clean

sd="staging/"
ip="orig.zip"

mkdir $sd > /dev/null
cd $sd > /dev/null
cat /dev/stdin > $ip

unzip $ip -d $ip.uncompressed > /dev/null
rm $ip > /dev/null

cd $ip.uncompressed > /dev/null
zip $ip -0 * > /dev/null

sed -E 's/_ptr_="0x[0-9a-f]{7}"/_ptr_="0xXXXXXXX"/' < $ip

cd .. > /dev/null
cd .. > /dev/null
rm -R -f $sd > /dev/null